### PR TITLE
Stylophone Showcase Template

### PR DESCRIPTION
**Pull request by Difegue**
👋 Didn't test this on WASM so hopefully it doesn't completely blow up because of the Markdown block.  

image

### CODE REVIEW

**Comment by Arlodotexe** [comment]
I've tested this and it does not appear to work in Web Assembly. Could you please either fix this or convert it to standard XAML instead of using Markdown?

**Review by Arlodotexe — CHANGES_REQUESTED** [review]
I've tested this and it does not appear to work in WASM. Could you please either fix this or convert it to regulard XAML instead of markdown?

**Comment by Difegue** [comment]
Uno has let me down again 😔 I've converted the block to bog-standard XAML and tested on WASM, looks fine.

**Comment by Arlodotexe** [comment]
Thank you for that. Before I merge this, could you fix the background contrast issue in dark mode?

image

**Review by Arlodotexe — APPROVED** [review]

**Pull request merged**
